feat: chan-less yoinking
melon095/Melonbot pull request #97
Opened 2023-01-31 00:33 UTC by brian6932

2023-01-31 00:48 UTC, JoachimFlottorp requested changes
This won't work in the current state.
For the bot to be able to modify the recipients emote-set, the bot first has to know that users emote-set at the moment it would mutate the current channels emote-set.

You would have to figure out the recipients users emote-set and have the `addEmote` function take in that data, rather than the `EmoteSet` function.

`getSevenTVAccount` should do that for you, it.

2023-02-01 03:51 UTC, brian6932 reviewed
The reason this was done was because ECMAScript regex look-behinds are fixed width, and there is no `\K`, so I wouldn't be able to extract and ignore both `#` and `@` chars with a single regex.
The other option was running a regex on each index, or checking first char of each index, the latter seemed preferable.

2023-02-01 04:17 UTC, brian6932 commented
Since multiple chans don't really make sense being filtered, I think potentially a better way to do this would be getting the first index of a chan, then removing that in a reduce step, leaving all the other indexes for the possibilities of them being emotes as well 🤔

2023-02-01 10:30 UTC, JoachimFlottorp requested changes

2023-02-01 10:30 UTC, JoachimFlottorp commented on src/commands/yoink.ts
> +		'If the current channel is not specified, target will be set to the current channel, and the bot will add to the user\'s channel',
Nitpicket. Could add an example here if there no channel is specified

2023-02-01 10:30 UTC, JoachimFlottorp commented on src/commands/yoink.ts
> +		let srcUser: any;
We can't use `any` here.

2023-02-02 13:25 UTC, JoachimFlottorp requested changes

2023-02-02 13:25 UTC, JoachimFlottorp commented on src/commands/yoink.ts
> +		const emoteset: string | undefined = (await gql.GetUser(await Bot.User.ResolveUsername(srcUser.username))).connections.find(i => i.platform === ConnectionPlatform.TWITCH)?.emote_set_id
unnecessary call to 7tv. We already have the user fetched `:58`. And im pretty sure the code above prevents `:95` from being required.

2023-02-02 16:51 UTC, JoachimFlottorp commented
![plink](https://user-images.githubusercontent.com/24413121/216389140-3f819bc0-250b-4973-9f7c-7998127857ed.gif)

Thank you for helping me. I very much appreciate it.

2023-02-02 16:52 UTC, JoachimFlottorp approved these changes

2023-02-02 16:55 UTC, merged